# Generated by Django 5.2.1 on 2025-05-26 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('teal', 'Teal')], default='indigo', max_length=20)),
                ('is_recurring', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='lesson_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='timetable_app.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('modified', 'Modified')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='timetable_app.lesson')),
            ],
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'day'], name='timetable_a_teacher_cf96f4_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['day', 'start_time'], name='timetable_a_day_493ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonexception',
            index=models.Index(fields=['lesson', 'date'], name='timetable_a_lesson__e4398c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonexception',
            index=models.Index(fields=['date'], name='timetable_a_date_63cd18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonexception',
            unique_together={('lesson', 'date')},
        ),
    ]
